############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

#[[main]]
#name = "About"
#url = "about/"
#weight = 2

#[[main]]
#name = "Contact"
#url = "contact/"
#weight = 3

[[main]]
name = "Posts"
url = "blog/"
weight = 3
hasChildren = true

#  [[main]]
#  parent = "Pages"
#  name = "Tags"
#  url = "tags/"
#  weight = 1

#  [[main]]
#  parent = "Pages"
#  name = "Categories"
#  url = "categories/"
#  weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Docs"
url = "https://docs.multiplatformkickstarter.com"
weight = 2

[[footer]]
name = "Multiplatform Kickstarter"
url = "https://www.multiplatformkickstarter.com"
weight = 3

[[footer]]
name = "About"
url = "about/"
weight = 4

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 4
