#################### default parameters ################################
# favicon
favicon = "images/favicon-32x32.png"
# logo
logo = "images/MKLogo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "298x"
# logo text will only show when logo is missing.
logo_text = "Multiplatform Kickstarter Blog"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Discover how to create multiplatform applications using Kotlin Multiplatform"
author = "Themefisher"
image = "images/MKLogo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@email.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# Posts related Titles & Contents
categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
read_more_button = "Read more"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = "Showing Post From"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog"]
# about widget content
about_widget_content = "Developed by industry veterans, *Multiplatform Kickstarter* is the first **template** with all the boilerplate code needed to help you to **kickstart your business in no time**."
# footer content
footer_content = ""
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = false
copyright = "<a href=\"https://storyset.com/user\">Illustrations by Storyset</a> | Copyright © 2023-2024 Multiplatform Kickstarter. All rights reserved."

# 404
error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Kotlin Multiplatform Blog"
title_small = "by Multiplatform Kickstarter"
image = "/images/sharing-articles-pana.svg"
background_image = "/images/banner-bg-shape.svg"
content = "Discover how to create multiplatform applications using Kotlin Multiplatform. \n\nDeveloped by industry veterans, *Multiplatform Kickstarter* is the first **template** with all the boilerplate code needed to help you to **kickstart your business in no time**. \n\nBased in **Kotlin Multiplatform** (KMP) and **Compose Multiplatform**, with few simple steps you will have up and running applications for **Android**, **iOS** and **Desktop** using **Ktor** as the server."
button_label = "Download now"
button_link = "https://github.com/MultiplatformKickstarter/adoptme"

# Advertise
#[advertisement]
#image = "images/promotion.png"
#link = "https://multiplatformkickstarter.com/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
#[subscription]
#enable = false
#newsletter_title = "Newsletter"
#newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
#newsletter_placeholder = "Type And Hit Enter"
#newsletter_reminder_a = "By Singing Up, You Agree To"
#newsletter_reminder_b = "Privacy Policy"
#newsletter_button = "Sign in"
# mailchimp subsciption
#mailchimp_form_action = ""
#mailchimp_form_name = ""


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/people/Multiplatform-Kickstarter/61553633924457/"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/mpkickstarter"

#[[social]]
#title = "instagram"
#icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
#link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/MultiplatformKickstarter"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
#link = "#"
